services:
  redis:
    image: redis:7-alpine
    ports:
      - "6379:6379"

  server:
    build: ./server
    env_file:
      - ./server/.env
    depends_on:
      - redis
    ports:
      - "5000:5000"
    develop:
      watch:
        - action: sync
          path: ./server
          target: /app
          ignore:
            - node_modules/
        - action: rebuild
          path: ./server/package.json

  client:
    build:
      context: ./client
      dockerfile: Dockerfile
      args:
        VITE_API_URL: http://localhost:5000/api
    ports:
      - "5173:5173"
    depends_on:
      - server
    develop:
      watch:
        - action: sync
          path: ./client
          target: /app
          ignore:
            - node_modules/
        - action: rebuild
          path: ./client/package.json
