services:
  redis:
    image: redis:7-alpine
    ports:
      - "6379:6379"
    environment:
      - REDIS_PASSWORD=${REDIS_PASSWORD}
    command: redis-server --requirepass ${REDIS_PASSWORD}

  server:
    image: ${SERVER_IMAGE:-billify-server:latest}
    env_file:
      - .env.staging
    depends_on:
      - redis
    ports:
      - "5000:5000"
    environment:
      - NODE_ENV=staging
      - REDIS_URL=redis://:${REDIS_PASSWORD}@redis:6379
    healthcheck:
      test: ["CMD", "curl", "-f", "http://localhost:5000/health"]
      interval: 30s
      timeout: 10s
      retries: 3
      start_period: 40s

  client:
    image: ${CLIENT_IMAGE:-billify-client:latest}
    ports:
      - "3000:80"
    depends_on:
      - server
    environment:
      - VITE_API_URL=https://staging-api.billify.com/api
    healthcheck:
      test: ["CMD", "curl", "-f", "http://localhost:80"]
      interval: 30s
      timeout: 10s
      retries: 3
      start_period: 40s

  nginx:
    image: nginx:alpine
    ports:
      - "80:80"
      - "443:443"
    volumes:
      - ./nginx.staging.conf:/etc/nginx/nginx.conf:ro
      - ./ssl/staging:/etc/ssl/staging:ro
    depends_on:
      - client
      - server
    restart: unless-stopped
